//! Named conversation store (owner request 2026-07-22).
//!
//! A conversation is a durable, user-saved record: its transcript segments,
//! the library documents linked to it, and timestamps. Unlike the automatic
//! per-listen session JSONL files (session.rs), conversations are explicit —
//! Stop offers to save, and saving again while the same conversation stays
//! open replaces the record with the fuller transcript (append semantics:
//! the UI keeps accumulating segments across Start/Stop while a conversation
//! is open).
//!
//! Storage: one pretty-printed JSON file per conversation under
//! `<app-data>/conversations/`.

use std::fs;
use std::path::PathBuf;

use serde::{Deserialize, Serialize};
use tauri::{AppHandle, Manager};

use convasist_core::asr::TranscriptSegment;
use convasist_core::CoreError;

use crate::session::now_unix_ms;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Conversation {
    pub id: String,
    pub title: String,
    pub created_at_unix_ms: u64,
    pub updated_at_unix_ms: u64,
    pub segments: Vec<TranscriptSegment>,
    /// Library document ids attached to this conversation.
    #[serde(default)]
    pub linked_docs: Vec<String>,
}

/// Catalog entry for the open/save menu.
#[derive(Debug, Clone, Serialize)]
pub struct ConversationSummary {
    pub id: String,
    pub title: String,
    pub created_at_unix_ms: u64,
    pub updated_at_unix_ms: u64,
    pub segment_count: u32,
    pub linked_docs: Vec<String>,
    pub preview: String,
}

fn conversations_dir(app: &AppHandle) -> Result<PathBuf, CoreError> {
    let dir = app
        .path()
        .app_data_dir()
        .map_err(|e| CoreError::Audio(format!("no app data dir: {e}")))?
        .join("conversations");
    fs::create_dir_all(&dir).map_err(|e| CoreError::Audio(e.to_string()))?;
    Ok(dir)
}

fn validate_id(id: &str) -> Result<(), CoreError> {
    // ids are generated by us, but never trust them as path components.
    if id.is_empty() || id.contains(['/', '\\', '.']) {
        return Err(CoreError::Audio("invalid conversation id".into()));
    }
    Ok(())
}

/// Title fallback when the user leaves it blank: the first words spoken,
/// else a plain marker the list can still render.
pub fn derive_title(segments: &[TranscriptSegment]) -> String {
    segments
        .iter()
        .find(|s| s.is_final && !s.text.trim().is_empty())
        .map(|s| {
            let text = s.text.trim();
            let title: String = text.chars().take(48).collect();
            if text.chars().count() > 48 {
                format!("{title}…")
            } else {
                title
            }
        })
        .unwrap_or_else(|| "Untitled conversation".to_string())
}

/// Create or update a conversation. With an existing `id`, the stored record
/// keeps its identity/created-at and takes the passed transcript + links
/// wholesale — the UI accumulates segments while a conversation stays open,
/// so re-saving is how "append" happens.
pub fn save(
    app: &AppHandle,
    id: Option<String>,
    title: Option<String>,
    segments: Vec<TranscriptSegment>,
    linked_docs: Vec<String>,
) -> Result<Conversation, CoreError> {
    let now = now_unix_ms();
    let finals: Vec<TranscriptSegment> = segments.into_iter().filter(|s| s.is_final).collect();
    let requested_title = title
        .map(|t| t.trim().to_string())
        .filter(|t| !t.is_empty());

    let conversation = match id {
        Some(id) => {
            validate_id(&id)?;
            let existing = load(app, &id).ok();
            Conversation {
                title: requested_title
                    .or_else(|| existing.as_ref().map(|c| c.title.clone()))
                    .unwrap_or_else(|| derive_title(&finals)),
                created_at_unix_ms: existing.map(|c| c.created_at_unix_ms).unwrap_or(now),
                updated_at_unix_ms: now,
                segments: finals,
                linked_docs,
                id,
            }
        }
        None => Conversation {
            id: format!("conv-{now}"),
            title: requested_title.unwrap_or_else(|| derive_title(&finals)),
            created_at_unix_ms: now,
            updated_at_unix_ms: now,
            segments: finals,
            linked_docs,
        },
    };

    let path = conversations_dir(app)?.join(format!("{}.json", conversation.id));
    let json =
        serde_json::to_string_pretty(&conversation).map_err(|e| CoreError::Audio(e.to_string()))?;
    fs::write(path, json).map_err(|e| CoreError::Audio(e.to_string()))?;
    Ok(conversation)
}

pub fn load(app: &AppHandle, id: &str) -> Result<Conversation, CoreError> {
    validate_id(id)?;
    let path = conversations_dir(app)?.join(format!("{id}.json"));
    let content = fs::read_to_string(path).map_err(|e| CoreError::Audio(e.to_string()))?;
    serde_json::from_str(&content).map_err(|e| CoreError::Audio(e.to_string()))
}

pub fn delete(app: &AppHandle, id: &str) -> Result<(), CoreError> {
    validate_id(id)?;
    let path = conversations_dir(app)?.join(format!("{id}.json"));
    fs::remove_file(path).map_err(|e| CoreError::Audio(e.to_string()))
}

pub fn list(app: &AppHandle) -> Result<Vec<ConversationSummary>, CoreError> {
    let dir = conversations_dir(app)?;
    let mut out = Vec::new();
    for entry in fs::read_dir(&dir)
        .map_err(|e| CoreError::Audio(e.to_string()))?
        .flatten()
    {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let Ok(content) = fs::read_to_string(&path) else {
            continue;
        };
        let Ok(conv) = serde_json::from_str::<Conversation>(&content) else {
            continue;
        };
        let preview = conv
            .segments
            .first()
            .map(|s| s.text.chars().take(60).collect())
            .unwrap_or_default();
        out.push(ConversationSummary {
            id: conv.id,
            title: conv.title,
            created_at_unix_ms: conv.created_at_unix_ms,
            updated_at_unix_ms: conv.updated_at_unix_ms,
            segment_count: conv.segments.len() as u32,
            linked_docs: conv.linked_docs,
            preview,
        });
    }
    out.sort_by_key(|c| std::cmp::Reverse(c.updated_at_unix_ms));
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use convasist_core::audio::StreamSide;

    fn seg(text: &str, is_final: bool) -> TranscriptSegment {
        TranscriptSegment {
            side: StreamSide::Outbound,
            seq: 0,
            text: text.into(),
            is_final,
            start_ms: 0,
            end_ms: 0,
            confidence: None,
            latency_ms: 0,
        }
    }

    #[test]
    fn title_derives_from_first_final_segment() {
        let segments = vec![
            seg("", true),
            seg("partial", false),
            seg("Hello there", true),
        ];
        assert_eq!(derive_title(&segments), "Hello there");
    }

    #[test]
    fn title_truncates_long_openers() {
        let long = "word ".repeat(30);
        let title = derive_title(&[seg(&long, true)]);
        assert!(title.chars().count() <= 49, "{title}");
        assert!(title.ends_with('…'));
    }

    #[test]
    fn title_falls_back_when_empty() {
        assert_eq!(derive_title(&[]), "Untitled conversation");
    }
}
